### ISSUE TITLE
Erstellung der Grafiken für den Kartenrücken und die -faces (5 SP)

### ISSUE THREAD

**Issue by XeLL777** [cprohinig/se2-uno#3]
Es soll sowohl die Grafik für den Kartenrücken sowie die Grafiken für die Kartenfaces erstellt werden. Im Zuge dieses Issues sollen lediglich die Karten des Grundspiels erstellt werden.

**Comment by cprohinig** [comment]
Durch @XeLL777 erledigt. Sonderkarten werden in separaten Issues abgearbeitet.
